---
###    This is the main playbook which calls other role(s) to setup the target host(s).
###
###    Note: 
###        Use "- hosts: all", if called from "Vagrantfile"
###
###
### - hosts: all

### - hosts: "{{ Dragon_Server_Hosts }}"

  - hosts: Dragon_Server_Hosts

    roles:

    - common
    - mysql_server
#    - oracle_12cR2_client
#    - dragon_server
    - dragon_server_part_1

# Run the Dragon Setup manually, and then run the Part 2

#    - dragon_server_part_2

...

